### ISSUE TITLE
grimp 3.2 packages are broken

### ISSUE THREAD

**Issue by apmorton** [conda-forge/grimp-feedstock#16]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
tar tf pkg-grimp-3.2-py311hda51310_0.tar.zst | sort
info/licenses/LICENSE
lib/python3.11/site-packages/grimp-3.2.dist-info/direct_url.json
lib/python3.11/site-packages/grimp-3.2.dist-info/INSTALLER
lib/python3.11/site-packages/grimp-3.2.dist-info/METADATA
lib/python3.11/site-packages/grimp-3.2.dist-info/RECORD
lib/python3.11/site-packages/grimp-3.2.dist-info/REQUESTED
lib/python3.11/site-packages/grimp-3.2.dist-info/WHEEL
lib/python3.11/site-packages/grimp/_rustgrimp.cpython-311-x86_64-linux-gnu.so
```

For some reason the 3.2 packages do not contain the python code, only the rust native module.

The recipe no longer builds 3.1 correctly either if you change the version/hash back.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by peterbygrave** [comment]
Thanks for the report. I confirmed your report for [linux-64/grimp-3.2-py311hda51310_0.conda](https://anaconda.org/conda-forge/grimp/3.2/download/linux-64/grimp-3.2-py311hda51310_0.conda), but pleased to say that the latest rebuild to include osx-arm64 3 days ago has fixed the existing builds for this issue. For example [linux-64/grimp-3.2-py311haaf45ca_0.conda](https://anaconda.org/conda-forge/grimp/3.2/download/linux-64/grimp-3.2-py311haaf45ca_0.conda) contains all the python code.

We are adding additional import checks to ensure a pure python code is available.

Thanks again
